import { Flex, Image } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>市政馨苑-小区状态</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex justifyContent={'center'} px={['0px', '100px']}>
        <Image src="/images/2022-4-25.jpg" alt="每日信息" />
      </Flex>
    </div>
  )
}

export default Home
